# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 275e6e18b326d87bc6f82445af3bbaaaa015923c2861e6d5aaa3c1f84a787af0141d3ea841f53dbf876328c036eb4a4aa517d15bfa5a2c28ef5371c15d3caa2b

test:
  secret_key_base: e653bcdc4dd5175aa2711b501ba4d4e21ee6e8cd9a3f1c619f023e9ab4f64b49d1bd60c399cf895ca7724a4dce30a679a54391e330f8ce1a5aeca6663f534aea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
